apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kernelprint.fullname" . }}-secrets
type: Opaque
stringData:
  apiKey: {{ .Values.secrets.apiKey | quote }}
  {{- if .Values.secrets.adminApiKey }}
  adminApiKey: {{ .Values.secrets.adminApiKey | quote }}
  {{- end }}
