services:
  templates:
    build:
      context: ./templates/kernelprint-templates/invoice-app
      dockerfile: Dockerfile
    ports:
      - "4173:4173"

  server:
    build:
      context: .
      dockerfile: docker/server.Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:5294
      KernelPrint__Engine__TemplateBaseUrl: http://templates:4173
      KernelPrint__Engine__Templates__AllowedHosts__0: "templates"
      KernelPrint__Engine__Templates__AllowedHosts__1: "localhost"
      KernelPrint__Engine__Templates__AllowedHosts__2: "127.0.0.1"
      KernelPrint__Security__ApiKey: "${KERNELPRINT_API_KEY:-change-me}"
      KernelPrint__Security__RequireApiKeyInDevelopment: "true"
      KernelPrint__Server__ReadinessHttpProbeUrl: "http://templates:4173/"
      KernelPrint__Admin__ApiKey: "${KERNELPRINT_ADMIN_API_KEY:-}"
    depends_on:
      - templates
    ports:
      - "5294:5294"
